blank_issues_enabled: false
contact_links:
  - name: Discussões Gerais
    url: https://github.com/MacMagazine/app-iOS/discussions
    about: Para perguntas ou conversas que não são bugs nem features
